apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: eetu-hakkinen-stonot
  labels:
    app: eetu-hakkinen-stonot

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: eetu-hakkinen-stonot

  template:
    metadata:
      labels:
        app: eetu-hakkinen-stonot
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/rasmus-nodejs-docker-webapp:latest
          name: eetu-hakkinen-stonot
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        service: workshop
