kind: Service
apiVersion: v1
metadata:
  labels:
    app: eetu-hakkinen-stonot
  name: eetu-hakkinen-stonot
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: eetu-hakkinen-stonot
